### ISSUE TITLE
error raise AttributeError("'{}' object has no attribute '{}'".format( AttributeError: 'ImageEncoderViT' object has no attribute 'last_attn'

### ISSUE THREAD

**Issue by Irennnne** [YuHengsss/Trident#4]
When I tried to run your demo, it threw this error. Could you give me some advice? Thank you!
```
Using cache found in /root/.cache/torch/hub/facebookresearch_dino_main
Traceback (most recent call last):
  File "trident_demo.py", line 97, in <module>
    trident_demo(img_path, name_list)
  File "trident_demo.py", line 90, in trident_demo
    seg_pred, seg_logits = model.predict(img_tensor, data_samples=None, debug_img_path=img_path)  # [1, H, W]
  File "/mmsegmentation/Trident/trident.py", line 248, in predict
    seg_logits = self.get_trident_seg(inputs, img_path, batch_img_metas)
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/mmsegmentation/Trident/trident.py", line 154, in get_trident_seg
    sam_enc_feats, sam_attn, sam_v, sam_valid_h, sam_valid_w = self.get_sam_feat(tmp_img, 16)
  File "/mmsegmentation/Trident/trident.py", line 121, in get_sam_feat
    sam_attn = self.sam_predictor.model.image_encoder.last_attn  # [1, 12, 64*64, 64*64]
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1185, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'ImageEncoderViT' object has no attribute 'last_attn'
```

**Comment by Irennnne** [comment]
I got another error when running the demo.  Could you give me some advice? 💔 I didn’t make any change to your code. Thx!
```
Traceback (most recent call last):
  File "trident_demo.py", line 97, in <module>
    trident_demo(img_path, name_list)
  File "trident_demo.py", line 90, in trident_demo
    seg_pred, seg_logits = model.predict(img_tensor, data_samples=None, debug_img_path=img_path)  # [1, H, W]
  File "/mmsegmentation/Trident/trident.py", line 248, in predict
    seg_logits = self.get_trident_seg(inputs, img_path, batch_img_metas)
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/mmsegmentation/Trident/trident.py", line 179, in get_trident_seg
    clip_features = self.clip.encode_image(img_batch.half(),external_feats=vfm_feats, beta=self.beta, gamma=self.gamma,
  File "/mmsegmentation/Trident/open_clip/model.py", line 266, in encode_image
    features = self.visual(image, external_feats, beta, gamma, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mmsegmentation/Trident/open_clip/transformer.py", line 528, in forward
    x = self.guidance_attn(blk.attn, blk.ln_1, x, token_size=token_size, **kwargs)
  File "/mmsegmentation/Trident/open_clip/transformer.py", line 635, in guidance_attn
    attn_weights = self.get_sam_sim(sam_v, sam_attn, cos_fac, num_heads, ref_neg).type_as(v) # 1, num_heads, dst_h*dst_w, dst_h*dst_w
  File "/mmsegmentation/Trident/open_clip/transformer.py", line 653, in get_sam_sim
    sim_thresh = torch.where(sim_thresh > 0.9, 0.9, sim_thresh)
RuntimeError: expected scalar type double but found c10::Half
```

**Comment by YuHengsss** [comment]
Hello, I have verfied pipeline in the readme and do not find any error above except  the torch version(should be 1.13
.1). The potential reason for these errors may come from the different python version. The one I used to develop this project is python 3.10, could you try the demo under this python version?

**Comment by Irennnne** [comment]
Thank you for your suggestion! I have successfully run your demo code by using another device. But I have a new question for the trident.py after running this code.
```
    def postprocess_result(self, seg_logits, data_samples, debug_img_path=None):
        batch_size = seg_logits.shape[0]
        for i in range(batch_size):
            seg_logits = seg_logits[i] * self.logit_scale
            seg_logits = seg_logits.softmax(0)  # n_queries * w * h

            num_cls, num_queries = max(self.query_idx) + 1, len(self.query_idx)
            if num_cls != num_queries:
                seg_fg = seg_logits[-num_cls+1:]
                seg_bg = seg_logits[:-num_cls+1].max(0)[0]
                seg_logits = torch.cat([seg_bg.unsqueeze(0), seg_fg], dim=0)

            seg_pred = seg_logits.argmax(0, keepdim=True)
            seg_pred[seg_logits.max(0, keepdim=True)[0] < self.prob_thd] = 0

            if self.debug and debug_img_path: tmp_img = debug_img_path
            else: tmp_img = data_samples[i].img_path
            if self.sam_refine:
                assert (data_samples is not None or debug_img_path is not None)
                refined_masks,scores,refined_logits,prompt_boxes = sam_refinement(tmp_img, seg_pred, seg_logits, num_cls,
                                                                                  self.sam_predictor, self.coarse_thresh, self.minimal_area,
                                                                                  self.sam_mask_coff, self.sam_iou_thresh,)
                seg_pred = refined_masks
                seg_logits = refined_logits

            if data_samples is None or self.debug:
                return seg_pred, seg_logits
            else:
                data_samples[i].set_data({
                    'seg_logits':
                        PixelData(**{'data': seg_logits}),
                    'pred_sem_seg':
                        PixelData(**{'data': seg_pred})
                })
        return data_samples
```
     ```
   for i in range(batch_size):
            seg_logits = seg_logits[i] * self.logit_scale
            seg_logits = seg_logits.softmax(0)  # n_queries * w * h
``` 
I am confused why the seg_logits becomes the first scaled seg_logits. Because when I use a larger batch size, it will throw error for the wrong shape of seg_logits. Could you explain a bit about this? Thank you for your help!

**Comment by Irennnne** [comment]
Thank you for your suggestion! I have successfully run your demo code by using another device. But I have a new question for the trident.py after running this code.

```

def postprocess_result(self, seg_logits, data_samples, debug_img_path=None):
        batch_size = seg_logits.shape[0]
        for i in range(batch_size):
            seg_logits = seg_logits[i] * self.logit_scale
            seg_logits = seg_logits.softmax(0)  # n_queries * w * h
            num_cls, num_queries = max(self.query_idx) + 1, len(self.query_idx)
            if num_cls != num_queries:
                seg_fg = seg_logits[-num_cls+1:]
                seg_bg = seg_logits[:-num_cls+1].max(0)[0]
                seg_logits = torch.cat([seg_bg.unsqueeze(0), seg_fg], dim=0)

            seg_pred = seg_logits.argmax(0, keepdim=True)
            seg_pred[seg_logits.max(0, keepdim=True)[0] < self.prob_thd] = 0

            if self.debug and debug_img_path: tmp_img = debug_img_path
            else: tmp_img = data_samples[i].img_path
            if self.sam_refine:
                assert (data_samples is not None or debug_img_path is not None)
                refined_masks,scores,refined_logits,prompt_boxes = sam_refinement(tmp_img, seg_pred, seg_logits, num_cls,
                                                                                  self.sam_predictor, self.coarse_thresh, self.minimal_area,
                                                                                  self.sam_mask_coff, self.sam_iou_thresh,)
                seg_pred = refined_masks
                seg_logits = refined_logits

            if data_samples is None or self.debug:
                return seg_pred, seg_logits
            else:
                data_samples[i].set_data({
                    'seg_logits':
                        PixelData(**{'data': seg_logits}),
                    'pred_sem_seg':
                        PixelData(**{'data': seg_pred})
                })
        return data_samples

```


For this code: 
```
for i in range(batch_size):
seg_logits = seg_logits[i] * self.logit_scale
seg_logits = seg_logits.softmax(0) # n_queries * w * h
```


I am confused why the seg_logits becomes the first scaled seg_logits. Because when I use a larger batch size, it will throw error for the wrong shape of seg_logits. Could you explain a bit about this? Thank you for your help!

**Comment by JarvisAI-7** [comment]
> When I tried to run your demo, it threw this error. Could you give me some advice? Thank you!
> 
> ```
> Using cache found in /root/.cache/torch/hub/facebookresearch_dino_main
> Traceback (most recent call last):
>   File "trident_demo.py", line 97, in <module>
>     trident_demo(img_path, name_list)
>   File "trident_demo.py", line 90, in trident_demo
>     seg_pred, seg_logits = model.predict(img_tensor, data_samples=None, debug_img_path=img_path)  # [1, H, W]
>   File "/mmsegmentation/Trident/trident.py", line 248, in predict
>     seg_logits = self.get_trident_seg(inputs, img_path, batch_img_metas)
>   File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
>     return func(*args, **kwargs)
>   File "/mmsegmentation/Trident/trident.py", line 154, in get_trident_seg
>     sam_enc_feats, sam_attn, sam_v, sam_valid_h, sam_valid_w = self.get_sam_feat(tmp_img, 16)
>   File "/mmsegmentation/Trident/trident.py", line 121, in get_sam_feat
>     sam_attn = self.sam_predictor.model.image_encoder.last_attn  # [1, 12, 64*64, 64*64]
>   File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1185, in __getattr__
>     raise AttributeError("'{}' object has no attribute '{}'".format(
> AttributeError: 'ImageEncoderViT' object has no attribute 'last_attn'
> ```

Hello, what kind of GPU do you need for training?
